// types/search-types.ts

// Typy pre ponuku (state)
export const STATE_OPTIONS = {
  ALL: "",
  SALE: "predaj",
  RENT: "prenajom",
} as const;

export const PROPERTY_OPTIONS = {
  ALL: "",
  APARTMENT: "byt",
  HOUSE: "dom",
  LAND: "pozemok",
} as const;

// Typy pre TypeScript
export type StateTypeValue = (typeof STATE_OPTIONS)[keyof typeof STATE_OPTIONS];
export type PropertyTypeValue =
  (typeof PROPERTY_OPTIONS)[keyof typeof PROPERTY_OPTIONS];

// Zoznam slovenských miest pre automatické dopĺňanie
export const SLOVAK_CITIES = [
  "Bratislava",
  "Košice",
  "Prešov",
  "Žilina",
  "Nitra",
  "Banská Bystrica",
  "Trnava",
  "Martin",
  "Trenčín",
  "Poprad",
  "Prievidza",
  "Zvolen",
  "Považská Bystrica",
  "Michalovce",
  "Nové Zámky",
  "Spišská Nová Ves",
  "Komárno",
  "Levice",
  "Humenné",
  "Bardejov",
  "Liptovský Mikuláš",
  "Lučenec",
  "Piešťany",
  "Ružomberok",
  "Topoľčany",
  "Čadca",
  "Dubnica nad Váhom",
  "Rimavská Sobota",
  "Partizánske",
  "Šaľa",
  "Hlohovec",
  "Dunajská Streda",
  "Galanta",
  "Námestovo",
  "Vranov nad Topľou",
  "Trebišov",
  "Snina",
  "Senica",
  "Rožňava",
  "Nové Mesto nad Váhom",
  "Bánovce nad Bebravou",
  "Žiar nad Hronom",
  "Dolný Kubín",
  "Brezno",
  "Stará Ľubovňa",
  "Sereď",
  "Skalica",
  "Veľký Krtíš",
  "Kysucké Nové Mesto",
  "Mýjava",
  "Revúca",
  "Sabinov",
  "Svätý Jur",
  "Modra",
  "Kežmarok",
  "Holíč",
  "Štúrovo",
  "Stupava",
  "Tvrdošín",
  "Kolarovo",
  "Veľký Meder",
  "Moldava nad Bodvou",
  "Šurany",
  "Medzilaborce",
  "Turzovka",
  "Lipany",
  "Krompachy",
  "Handlová",
  "Svit",
  "Veľké Kapušany",
  "Stropkov",
  "Kremnica",
  "Šamorín",
  "Gelnica",
  "Krásno nad Kysucou",
  "Bytča",
  "Liptovský Hrádok",
  "Turčianske Teplice",
];
